/* DeepRise UI & Interaction Layer v14.6
   Presentation-only upgrade: restores compact entry cues, improves forecast readability,
   expands safe tap targets and polishes mobile/desktop layout. Scanner logic is untouched.
*/
(()=>{'use strict';
if(window.DeepRiseUIV146)return;
const VERSION='14.6';
const lang=()=>{try{return typeof currentLang!=='undefined'?currentLang:(localStorage.getItem('deeprise_language')||'en')}catch(e){return localStorage.getItem('deeprise_language')||'en'}};
const market=()=>{try{return typeof marketData!=='undefined'&&Array.isArray(marketData)?marketData:[]}catch(e){return[]}};
const P={
 en:{candle:'Confirmation candle',volume:'Volume',momentum:'Momentum',entry:'Entry gate',ready:'READY',wait:'WAIT',weak:'Weak',building:'Building',confirmed:'Confirmed',bull:'Bullish',bear:'Bearish',neutral:'Neutral',tap:'Tap coin for details',noCandle:'No confirmation yet'},
 ar:{candle:'شمعة التأكيد',volume:'الحجم (Volume)',momentum:'الزخم',entry:'حالة الدخول',ready:'جاهز',wait:'انتظار',weak:'ضعيف',building:'يتحسن',confirmed:'مؤكد',bull:'صاعد',bear:'هابط',neutral:'محايد',tap:'اضغط على العملة لفتح التفاصيل',noCandle:'لا توجد شمعة تأكيد بعد'},
 ru:{candle:'Свеча подтверждения',volume:'Объём',momentum:'Импульс',entry:'Вход',ready:'ГОТОВО',wait:'ЖДАТЬ',weak:'Слабый',building:'Формируется',confirmed:'Подтверждён',bull:'Бычий',bear:'Медвежий',neutral:'Нейтральный',tap:'Нажмите на монету для деталей',noCandle:'Подтверждающей свечи пока нет'}
};
const t=k=>(P[lang()]||P.en)[k]||k;
function css(){if(document.getElementById('dr-ui-v146-css'))return;const s=document.createElement('style');s.id='dr-ui-v146-css';s.textContent=`
:root{--dr-card:#071522;--dr-card2:#091b2a;--dr-line:#1a3a52;--dr-soft:#7893a8}
.card,.pick,.chart-panel,.signal-results-panel{box-shadow:0 10px 34px rgba(0,0,0,.18)}
.card{position:relative;overflow:hidden;transition:border-color .18s ease,transform .18s ease,box-shadow .18s ease}.card:active{transform:scale(.998)}
.coin-head{padding-bottom:9px;border-bottom:1px solid rgba(31,67,92,.58)}.coin-head>div:first-child{min-width:0}
.dr-coin-hit{position:relative;display:block;min-height:52px;margin:-7px;padding:7px;border-radius:11px;cursor:pointer;touch-action:manipulation;-webkit-user-select:none;user-select:none;outline:none}.dr-coin-hit:active{background:rgba(53,224,161,.07)}.dr-coin-hit:focus-visible{box-shadow:0 0 0 2px rgba(53,224,161,.55)}
.sym-link{display:inline-flex!important;align-items:center;min-height:36px;padding:2px 5px 2px 0;font-size:20px;letter-spacing:.1px;touch-action:manipulation}html[dir="rtl"] .sym-link{padding:2px 0 2px 5px}.dr-tap-hint{display:block;margin-top:2px;color:#5f7d94;font-size:9px;font-weight:600;line-height:1.2}
.dr-entry-strip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin:10px 0 11px}.dr-entry-chip{min-width:0;background:linear-gradient(180deg,#081a29,#06131f);border:1px solid #17364d;border-radius:11px;padding:9px 10px}.dr-entry-chip small{display:block;color:#6f8ba1;font-size:9px;font-weight:700;margin-bottom:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dr-entry-chip b{display:block;color:#dcecff;font-size:11px;line-height:1.28;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dr-entry-chip.ok{border-color:#20664f;background:linear-gradient(180deg,#0a241d,#071813)}.dr-entry-chip.ok b{color:#49e6ad}.dr-entry-chip.warn{border-color:#6b5b24;background:linear-gradient(180deg,#211d0d,#151207)}.dr-entry-chip.warn b{color:#ffd166}.dr-entry-chip.bad{border-color:#6b303b;background:linear-gradient(180deg,#251318,#180b0f)}.dr-entry-chip.bad b{color:#ff7a86}.dr-entry-chip.info b{color:#8ccaff}
.dr-pick-cues{display:flex;gap:6px;flex-wrap:wrap;margin:5px 0 8px}.dr-pick-cue{font-size:9px;font-weight:800;padding:5px 7px;border-radius:999px;border:1px solid #1c3c53;background:#071827;color:#90aabd}.dr-pick-cue.ok{border-color:#20664f;color:#49e6ad;background:#0a211b}.dr-pick-cue.warn{border-color:#665824;color:#ffd166;background:#211d0d}.dr-pick-cue.bad{border-color:#70303b;color:#ff7a86;background:#261218}
.data{margin-top:2px}.box{border:1px solid rgba(24,57,80,.56)}.box .label{letter-spacing:.35px}.box .value{line-height:1.3}.confirm,.early,.decision{border-radius:12px!important;margin-top:9px!important}
.ncf-detail{padding:15px!important;background:linear-gradient(180deg,#06131f,#050f19)!important}.ncf-detail-head{display:block!important;margin-bottom:12px!important}.ncf-detail-head>b{display:block;font-size:16px!important;line-height:1.35}.ncf-detail-head span{display:block!important;max-width:none!important;text-align:start!important;margin-top:6px;padding:8px 10px;border-radius:9px;background:#081827;color:#7894aa!important;font-size:10px!important;line-height:1.55!important}.ncf-detail-grid{gap:10px!important}.ncf-detail-card{padding:13px!important;border-radius:13px!important;box-shadow:0 7px 22px rgba(0,0,0,.18)!important;overflow:hidden}.ncf-detail-top{align-items:center!important;padding-bottom:10px;border-bottom:1px solid rgba(31,67,92,.55);font-size:12px!important}.ncf-detail-top>span{font-weight:800;color:#b8cada}.ncf-detail-top>b{font-size:14px!important;white-space:nowrap}.ncf-detail-body{display:grid!important;grid-template-columns:minmax(0,.82fr) minmax(0,1.18fr)!important;gap:8px!important;margin-top:10px!important}.ncf-detail-body>span{display:block!important;min-width:0;padding:9px 10px;border:1px solid rgba(25,57,80,.72);border-radius:10px;background:#071725;color:#91aabd!important;font-size:10px!important;line-height:1.55!important;overflow-wrap:anywhere}.ncf-detail-body>span b{display:block;color:#d9e8f4;margin-bottom:3px;font-size:9px;text-transform:uppercase;letter-spacing:.25px}.ncf-detail-body>span:first-child{grid-column:1/-1;color:#dcecff!important;font-size:12px!important;font-weight:800;background:#091b2a;border-color:#21465f}.ncf-detail-body>span:nth-child(3){grid-column:1/-1}.ncf-strip{margin-top:8px!important}.ncf-btn{min-height:48px!important;border-radius:11px!important;padding:8px 10px!important}.ncf-btn b{font-size:12px!important}.ncf-btn small{font-size:9px!important}
.chart-panel{border-radius:16px!important}.chart-analysis{gap:9px!important;padding:13px!important}.chart-analysis .box{border-radius:11px!important;padding:11px!important}.forecast-pro{padding:14px!important}.forecast-grid{gap:9px!important}.forecast-note{border-radius:11px!important;padding:11px!important}.forecast-note span{line-height:1.65!important}.forecast-warning{padding:9px 10px;border:1px solid #17364d;border-radius:10px;background:#071522;line-height:1.6!important}.chart-actions{scrollbar-width:none}.chart-actions::-webkit-scrollbar{display:none}.chart-btn{min-height:42px;touch-action:manipulation}
@media(max-width:820px){body{padding-bottom:calc(84px + env(safe-area-inset-bottom,0px))!important}.container{width:96%!important;margin-top:8px!important}.card{padding:13px!important;margin-bottom:11px!important;border-radius:14px!important}.hero{border-radius:14px!important}.pick{padding:12px!important}.coin-head{align-items:flex-start!important;gap:7px!important}.coin-head .badges{gap:4px!important}.badge{padding:5px 7px!important}.dr-entry-strip{grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.dr-entry-chip{padding:9px}.dr-entry-chip b{font-size:11px}.data{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:7px!important}.box{padding:9px!important;min-height:61px!important}.label{font-size:8.5px!important}.value{font-size:12px!important}.ncf-detail{padding:12px!important}.ncf-detail-head>b{font-size:15px!important}.ncf-detail-body{grid-template-columns:1fr!important}.ncf-detail-body>span,.ncf-detail-body>span:first-child,.ncf-detail-body>span:nth-child(3){grid-column:1!important}.ncf-detail-body>span{font-size:10.5px!important}.ncf-detail-top>b{font-size:13px!important}.chart-analysis{grid-template-columns:repeat(2,minmax(0,1fr))!important}.chart-head{padding:12px!important}.chart-actions{gap:5px!important}.chart-btn{min-width:56px;padding:9px 11px!important}.dr-bottom-nav{height:66px!important;border-radius:20px!important;left:7px!important;right:7px!important}.dr-nav{font-size:10.5px!important}.dr-nav .ico{font-size:21px!important}}
@media(max-width:390px){.dr-entry-strip{gap:6px}.dr-entry-chip{padding:8px}.dr-entry-chip small{font-size:8px}.dr-entry-chip b{font-size:10px}.sym-link{font-size:19px}.ncf-detail-top{gap:5px!important}.ncf-detail-top>b{font-size:12px!important}.chart-analysis{gap:6px!important}}
@media(hover:hover){.dr-coin-hit:hover{background:rgba(101,184,255,.055)}.card:hover{border-color:#244963;box-shadow:0 12px 38px rgba(0,0,0,.23)}}
`;document.head.appendChild(s)}
function symbolFrom(host){const sym=host?.querySelector?.('.sym')||host?.closest?.('.card,.pick')?.querySelector?.('.sym');if(!sym)return'';let raw=(sym.textContent||'').toUpperCase().replace(/\s/g,'').replace(/[^A-Z0-9/]/g,'');let base=raw.split('/')[0].replace(/USDT$/,'');return base?base+'USDT':''}
function candleName(x){const raw=String(x?.candle?.name||'').trim();if(!raw)return t('noCandle');if(lang()!=='ar')return raw;const s=raw.toLowerCase();if(s.includes('bullish engulf'))return'ابتلاع صاعد';if(s.includes('bearish engulf'))return'ابتلاع هابط';if(s.includes('hammer'))return'مطرقة';if(s.includes('shooting'))return'شهاب';if(s.includes('doji'))return'دوجي';if(s.includes('bull'))return'شمعة صاعدة';if(s.includes('bear'))return'شمعة هابطة';return raw}
function stateFor(x){const dir=x?.direction||'WAIT',candleOk=dir==='LONG'?!!x?.candle?.bull:dir==='SHORT'?!!x?.candle?.bear:false,vr=Number(x?.volumeRatio||0),rsi=Number(x?.rsi||50);let volText=vr>=1.5?t('confirmed'):vr>=1.15?t('building'):t('weak'),volClass=vr>=1.5?'ok':vr>=1.15?'warn':'bad';let momText=t('neutral'),momClass='warn';if(rsi>=53&&rsi<=70){momText=t('bull')+' • RSI '+rsi.toFixed(0);momClass='ok'}else if(rsi>=30&&rsi<=47){momText=t('bear')+' • RSI '+rsi.toFixed(0);momClass='bad'}else{momText=t('neutral')+' • RSI '+rsi.toFixed(0);momClass='warn'}const ready=(dir==='LONG'||dir==='SHORT')&&candleOk&&vr>=1.25;return{candleOk,vr,volText,volClass,momText,momClass,gateText:ready?t('ready'):t('wait'),gateClass:ready?'ok':'warn'}}
function chip(label,value,cls='info'){return `<div class="dr-entry-chip ${cls}"><small>${label}</small><b>${value}</b></div>`}
function decorateCard(card){const symbol=symbolFrom(card),x=market().find(a=>a.symbol===symbol);if(!symbol||!x)return;const head=card.querySelector('.coin-head'),hit=head?.querySelector(':scope > div:first-child');if(hit){hit.classList.add('dr-coin-hit');hit.dataset.drSymbol=symbol;hit.setAttribute('role','button');hit.setAttribute('tabindex','0');let hint=hit.querySelector('.dr-tap-hint');if(!hint){hint=document.createElement('small');hint.className='dr-tap-hint';const price=hit.querySelector('.small');price?.insertAdjacentElement('afterend',hint)}if(hint&&hint.textContent!==t('tap'))hint.textContent=t('tap')}let strip=card.querySelector(':scope > .dr-entry-strip');if(!strip){strip=document.createElement('div');strip.className='dr-entry-strip';head?.insertAdjacentElement('afterend',strip)}const s=stateFor(x),cCls=s.candleOk?'ok':(x.candle?.bull||x.candle?.bear?'warn':'bad'),html=chip(t('candle'),candleName(x),cCls)+chip(t('volume'),s.vr.toFixed(2)+'× • '+s.volText,s.volClass)+chip(t('momentum'),s.momText,s.momClass)+chip(t('entry'),s.gateText,s.gateClass);if(strip.innerHTML!==html)strip.innerHTML=html}
function decoratePick(pick){const symbol=symbolFrom(pick),x=market().find(a=>a.symbol===symbol);if(!symbol||!x)return;const sym=pick.querySelector('.sym');if(sym){sym.dataset.drSymbol=symbol;sym.setAttribute('role','button');sym.setAttribute('tabindex','0')}let cues=pick.querySelector('.dr-pick-cues');if(!cues){cues=document.createElement('div');cues.className='dr-pick-cues';sym?.insertAdjacentElement('afterend',cues)}const s=stateFor(x),html=`<span class="dr-pick-cue ${s.candleOk?'ok':'warn'}">🕯 ${candleName(x)}</span><span class="dr-pick-cue ${s.volClass}">VOL ${s.vr.toFixed(2)}×</span><span class="dr-pick-cue ${s.gateClass}">${t('entry')}: ${s.gateText}</span>`;if(cues.innerHTML!==html)cues.innerHTML=html}
function organizeForecast(){const d=document.getElementById('ncf-chart-detail');if(!d)return;d.querySelectorAll('.ncf-detail-card').forEach(card=>{const spans=card.querySelectorAll('.ncf-detail-body>span');spans.forEach((s,i)=>{s.dataset.drForecastPart=['shape','projected','evidence','learning'][i]||'info'});card.setAttribute('aria-label',(card.querySelector('.ncf-detail-top')?.textContent||'').trim())})}
function decorate(){document.querySelectorAll('#results .card').forEach(decorateCard);document.querySelectorAll('#top3 .pick').forEach(decoratePick);organizeForecast()}
function safeOpen(symbol){if(!symbol)return;try{if(typeof openChart==='function')openChart(symbol)}catch(e){}}
function events(){document.addEventListener('click',e=>{const hit=e.target.closest('.dr-coin-hit');if(!hit)return;if(e.target.closest('button,a,input,select,textarea,.ncf-strip'))return;if(e.target.closest('.sym-link'))return;safeOpen(hit.dataset.drSymbol)},false);document.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const hit=e.target.closest('.dr-coin-hit,.sym[data-dr-symbol]');if(!hit)return;e.preventDefault();safeOpen(hit.dataset.drSymbol)},false)}
function boot(){css();events();decorate();let timer=null;const mo=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(decorate,90)});['results','top3','chartPanel'].forEach(id=>{const el=document.getElementById(id);if(el)mo.observe(el,{childList:true,subtree:true})});setInterval(decorate,4000)}
window.DeepRiseUIV146={version:VERSION,refresh:decorate};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();