(()=>{'use strict';
const mobile=()=>matchMedia('(max-width:820px)').matches;
const DASH='https://us.posthog.com/project/582338/dashboard/2042360';
const lang=()=>localStorage.getItem('deeprise_language')||'en';
const T={en:{home:'Home',signals:'Signals',radar:'Radar',chart:'Chart',more:'More',live:'LIVE',sub:'V14.5 PRO Mobile',menu:'Quick tools',top:'Top 5',pump:'Pump',timing:'Timing',learn:'Learning',analytics:'Analytics',analyticsTitle:'📊 DeepRise Analytics',private:'Private owner analytics',tracking:'Tracking',connected:'Connected',opens:'App opens',scans:'Scans',charts:'Charts',radars:'Radar',session:'Session',device:'Mode',dashboard:'Open full private dashboard',note:'Global visitors, countries and devices stay private in PostHog. This panel shows this device activity only.',quality:'Signal Conditions',entryTiming:'Entry timing',ready:'ENTRY READY — all 6 conditions confirmed',analysis:'Waiting deep analysis',waiting:'WAITING',retest:'CONFIRMED — waiting final trigger',forming:'SETUP FORMING'},ar:{home:'الرئيسية',signals:'التوصيات',radar:'الرادار',chart:'الشارت',more:'المزيد',live:'مباشر',sub:'V14.5 PRO تطبيق',menu:'أدوات سريعة',top:'أفضل 5',pump:'البامب',timing:'التوقيت',learn:'التعلم',analytics:'الإحصائيات',analyticsTitle:'📊 إحصائيات DeepRise',private:'إحصائيات خاصة بالمالك',tracking:'التتبع',connected:'متصل',opens:'فتح التطبيق',scans:'عمليات الفحص',charts:'فتح الشارت',radars:'فتح الرادار',session:'مدة الجلسة',device:'الوضع',dashboard:'فتح لوحة الإحصائيات الكاملة',note:'إجمالي الزوار والدول والأجهزة يبقى خاصًا داخل PostHog. هذه الشاشة تعرض نشاط هذا الجهاز فقط.',quality:'شروط الإشارة الستة',entryTiming:'توقيت الدخول',ready:'الدخول جاهز — تحققت الشروط الستة',analysis:'بانتظار التحليل العميق',waiting:'بانتظار',retest:'تم التأكيد — بانتظار محفز الدخول الأخير',forming:'الإعداد يتكوّن'},ru:{home:'Главная',signals:'Сигналы',radar:'Радар',chart:'График',more:'Ещё',live:'LIVE',sub:'V14.5 PRO Mobile',menu:'Быстрые',top:'Top 5',pump:'Pump',timing:'Timing',learn:'Learning',analytics:'Аналитика',analyticsTitle:'📊 DeepRise Analytics',private:'Private owner analytics',tracking:'Tracking',connected:'Connected',opens:'App opens',scans:'Scans',charts:'Charts',radars:'Radar',session:'Session',device:'Mode',dashboard:'Open private dashboard',note:'Global visitors, countries and devices remain private in PostHog. This panel shows this device only.',quality:'6 условий сигнала',entryTiming:'Время входа',ready:'ВХОД ГОТОВ — все 6 условий выполнены',analysis:'Ожидание глубокого анализа',waiting:'ОЖИДАНИЕ',retest:'ПОДТВЕРЖДЕНО — ждём финальный триггер',forming:'СЕТАП ФОРМИРУЕТСЯ'}};
const q=k=>(T[lang()]||T.en)[k]||k;
const C={
 en:{'15m trend':'15m trend','1H trend':'1H trend','Score ≥ 72':'Score ≥ 72','Volume ≥ 1.2×':'Volume ≥ 1.2×','Confirmation candle':'Confirmation candle','Liquidity + R:R':'Liquidity + R:R'},
 ar:{'15m trend':'اتجاه 15 دقيقة','1H trend':'اتجاه 1 ساعة','Score ≥ 72':'السكور ≥ 72','Volume ≥ 1.2×':'الحجم ≥ 1.2×','Confirmation candle':'شمعة التأكيد','Liquidity + R:R':'السيولة + العائد/المخاطرة'},
 ru:{'15m trend':'Тренд 15м','1H trend':'Тренд 1ч','Score ≥ 72':'Score ≥ 72','Volume ≥ 1.2×':'Объём ≥ 1.2×','Confirmation candle':'Свеча подтверждения','Liquidity + R:R':'Ликвидность + R:R'}
};
const ct=k=>(C[lang()]||C.en)[k]||k;
function marketArray(){try{return typeof marketData!=='undefined'&&Array.isArray(marketData)?marketData:[]}catch(e){return[]}}
function cardSymbol(card){let s=card?.dataset?.drSymbol||card?.dataset?.symbol;if(s)return s;let b=card?.querySelector('.sym')?.textContent?.trim()?.split('/')[0];return b?b+'USDT':''}
function analysisFor(sym){if(!sym)return null;try{let a=window.DeepRiseBinanceUniverse?.state?.analyzed?.get?.(sym);if(a)return a}catch(e){}return marketArray().find(x=>x.symbol===sym)||null}
function conditionStatus(x){if(!x)return null;try{if(window.DeepRiseV13?.quality)return window.DeepRiseV13.quality(x)}catch(e){}const side=x._rawDirection||x.direction||'WAIT',long=side==='LONG',short=side==='SHORT';if(!long&&!short)return{side:'WAIT',count:0,state:'WAIT',items:[]};const items=[['15m trend',long?x.e20>x.e50:x.e20<x.e50],['1H trend',long?!!x.h1Bull:!!x.h1Bear],['Score ≥ 72',Number(x.score)>=72],['Volume ≥ 1.2×',Number(x.volumeRatio)>=1.2],['Confirmation candle',long?!!x.candle?.bull:!!x.candle?.bear],['Liquidity + R:R',Number(x.quoteVolume)>=20000000&&Number(x.rr)>=1.8&&Number(x.atrPct)<=6]];const count=items.filter(v=>v[1]).length;return{side,count,state:count>=6?'READY':count===5?'CONFIRMED':count===4?'FORMING':'WAIT',items}}
function timingText(st){if(!st)return q('analysis');if(st.count===6)return q('ready');const missing=st.items.filter(v=>!v[1]).map(v=>ct(v[0]));if(st.count===5)return q('retest')+(missing.length?' • '+q('waiting')+': '+missing.join(' + '):'');if(st.count===4)return q('forming')+(missing.length?' • '+q('waiting')+': '+missing.join(' + '):'');return q('waiting')+(missing.length?': '+missing.join(' + '):' confirmation')}
let conditionPaintQueued=false;
function decorateConditions(){conditionPaintQueued=false;document.querySelectorAll('#results .card').forEach(card=>{const sym=cardSymbol(card),x=analysisFor(sym),st=conditionStatus(x);let box=card.querySelector('.dr-v13-quality');if(!box){box=document.createElement('div');box.className='dr-v13-quality dr-six-conditions';const anchor=card.querySelector('.coin-head');anchor?.insertAdjacentElement('afterend',box)}if(!box)return;if(!st||!st.items.length){box.innerHTML=`<div class="dr-six-head"><b>${q('quality')}: <span class="yellow">0/6</span></b><strong class="yellow">${q('analysis')}</strong></div><div class="dr-entry-timing yellow">⏱ ${q('entryTiming')}: ${q('analysis')}</div>`;return}const checks=st.items.map(v=>`<span class="${v[1]?'ok':'no'}">${v[1]?'✓':'○'} ${ct(v[0])}</span>`).join('');const cls=st.count===6?'green':st.count>=5?'blue':st.count===4?'yellow':'red';box.innerHTML=`<div class="dr-six-head"><b>${q('quality')}: <span class="${cls}">${st.count}/6</span></b><strong class="${cls}">${st.state}</strong></div><div class="dr-v13-checks">${checks}</div><div class="dr-entry-timing ${cls}">⏱ ${q('entryTiming')}: ${timingText(st)}</div>`})}
function queueConditionPaint(){if(conditionPaintQueued)return;conditionPaintQueued=true;requestAnimationFrame(()=>setTimeout(decorateConditions,0))}
const condObserver=new MutationObserver(queueConditionPaint);addEventListener('DOMContentLoaded',()=>{const results=document.getElementById('results');if(results)condObserver.observe(results,{childList:true,subtree:true});queueConditionPaint()});addEventListener('load',()=>{queueConditionPaint();setTimeout(queueConditionPaint,1600)});
const conditionCss=document.createElement('style');conditionCss.textContent=`.dr-six-conditions{display:block!important}.dr-six-head{display:flex;justify-content:space-between;gap:8px;align-items:center;font-size:11px}.dr-six-head strong{font-size:10px;text-align:right}.dr-entry-timing{margin-top:8px;padding-top:7px;border-top:1px solid #173148;font-size:10px;line-height:1.45;font-weight:700}.dr-v13-checks{display:flex!important;flex-wrap:wrap;gap:5px;margin-top:8px}.dr-v13-checks span{display:inline-block!important;font-size:9px;border:1px solid #1a3448;border-radius:15px;padding:4px 7px;color:#718ba1}.dr-v13-checks .ok{color:#35e0a1;border-color:#1f614e;background:rgba(53,224,161,.05)}.dr-v13-checks .no{color:#8fa4b6;background:rgba(127,153,175,.04)}`;document.head.appendChild(conditionCss);
if(!mobile())return;
function clickText(words){const els=[...document.querySelectorAll('button,a,[role=button]')];let e=els.find(x=>words.some(w=>(x.textContent||'').toLowerCase().includes(w)));if(e){e.click();return true}return false}
function dur(ms){let s=Math.max(0,Math.floor(ms/1000));if(s<60)return s+'s';let m=Math.floor(s/60);return m<60?m+'m':Math.floor(m/60)+'h '+m%60+'m'}
function analyticsPanel(){let old=document.querySelector('.dr-analytics-modal');if(old){old.remove();return}let a=window.DeepRiseAnalytics?.getLocalStats?.()||{opens:0,scans:0,charts:0,radar:0,sessionElapsedMs:0,displayMode:'browser',connected:false};let p=document.createElement('div');p.className='dr-analytics-modal';p.innerHTML=`<div class="dr-analytics-card"><div class="dr-analytics-head"><div><b>${q('analyticsTitle')}</b><small>${q('private')}</small></div><button data-aclose>✕</button></div><div class="dr-track-status"><span>● ${q('tracking')}</span><b>${a.connected?q('connected'):'LOCAL'}</b></div><div class="dr-analytics-grid"><div><small>${q('opens')}</small><b>${a.opens||0}</b></div><div><small>${q('scans')}</small><b>${a.scans||0}</b></div><div><small>${q('charts')}</small><b>${a.charts||0}</b></div><div><small>${q('radars')}</small><b>${a.radar||0}</b></div><div><small>${q('session')}</small><b>${dur(a.sessionElapsedMs||0)}</b></div><div><small>${q('device')}</small><b>${a.displayMode||'browser'}</b></div></div><p>${q('note')}</p><a class="dr-dashboard-btn" href="${DASH}" target="_blank" rel="noopener">${q('dashboard')} ↗</a></div>`;document.body.appendChild(p);p.querySelector('[data-aclose]').onclick=()=>p.remove();p.onclick=e=>{if(e.target===p)p.remove()};window.DeepRiseAnalytics?.capture?.('analytics_panel_open')}
function goHome(){try{document.querySelector('.dr-quick-sheet')?.classList.remove('active');document.querySelector('.dr-analytics-modal')?.remove();document.getElementById('chartPanel')?.classList.remove('active');document.getElementById('signalResultsPanel')?.classList.remove('active');document.querySelectorAll('.signal-results-panel.active').forEach(x=>x.classList.remove('active'));document.getElementById('dropdown')?.classList.remove('active');const s=document.getElementById('search');if(s)s.value='';try{currentFilter='all'}catch(e){}document.querySelectorAll('.filter[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));try{if(typeof render==='function')render()}catch(e){}document.querySelectorAll('.dr-nav').forEach(x=>x.classList.toggle('active',x.dataset.nav==='home'));history.replaceState(null,'',location.pathname+location.search);scrollTo({top:0,behavior:'smooth'});setTimeout(queueConditionPaint,100)}catch(e){scrollTo({top:0,behavior:'smooth'})}}
function nav(kind){document.querySelectorAll('.dr-nav').forEach(x=>x.classList.toggle('active',x.dataset.nav===kind));if(kind==='home')return goHome();if(kind==='signals'){if(!clickText(['top 5','أفضل 5','топ-5','results','نتائج']))document.querySelector('.signal-results-panel')?.scrollIntoView({behavior:'smooth'})}if(kind==='radar'){if(!clickText(['pre-move','radar','الرادار','pump confidence','ثقة البامب']))document.querySelector('[id*=intelligence],[id*=pump]')?.scrollIntoView({behavior:'smooth'})}if(kind==='chart'){if(!clickText(['chart','الشارت','график']))document.querySelector('canvas')?.scrollIntoView({behavior:'smooth',block:'center'})}if(kind==='more')document.querySelector('.dr-quick-sheet')?.classList.toggle('active')}
function build(){document.body.classList.add('dr-app-mode');let h=document.createElement('header');h.className='dr-mobile-header';h.innerHTML=`<div class="dr-mobile-brand"><img src="icon.svg"><div>DeepRise<small>${q('sub')}</small></div></div><div class="dr-live">● ${q('live')}</div>`;document.body.prepend(h);let sheet=document.createElement('div');sheet.className='dr-quick-sheet';sheet.innerHTML=`<b style="display:block;margin:2px 2px 10px">${q('menu')}</b><div class="dr-quick-grid"><button data-go="top"><b>🏆 ${q('top')}</b>Performance tracking</button><button data-go="pump"><b>🔥 ${q('pump')}</b>Confidence radar</button><button data-go="timing"><b>⏱ ${q('timing')}</b>Expected window</button><button data-go="learn"><b>🧠 ${q('learn')}</b>Adaptive engine</button><button data-go="analytics" class="dr-analytics-tool"><b>📊 ${q('analytics')}</b>${q('private')}</button></div>`;document.body.appendChild(sheet);sheet.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{const k=b.dataset.go;if(k==='analytics'){sheet.classList.remove('active');analyticsPanel();return}const m={top:['top 5','أفضل 5','топ-5'],pump:['pump confidence','ثقة البامب'],timing:['pump timing','توقيت البامب'],learn:['adaptive learning','التعلم التكيفي']};clickText(m[k]);sheet.classList.remove('active')});let n=document.createElement('nav');n.className='dr-bottom-nav';n.innerHTML=`<button class="dr-nav active" data-nav="home"><span class="ico">⌂</span>${q('home')}</button><button class="dr-nav" data-nav="signals"><span class="ico">◎</span>${q('signals')}</button><button class="dr-nav" data-nav="radar"><span class="ico">◉</span>${q('radar')}</button><button class="dr-nav" data-nav="chart"><span class="ico">⌁</span>${q('chart')}</button><button class="dr-nav" data-nav="more"><span class="ico">•••</span>${q('more')}</button>`;document.body.appendChild(n);n.querySelectorAll('.dr-nav').forEach(b=>b.onclick=()=>nav(b.dataset.nav));if(matchMedia('(display-mode: standalone)').matches||navigator.standalone){let t=document.createElement('div');t.className='dr-app-toast';t.textContent='⚡ DeepRise App Mode';document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}queueConditionPaint()}
addEventListener('load',()=>setTimeout(build,1300));})();