(()=>{'use strict';
const L=()=>localStorage.getItem('deeprise_language')||'en';
const copy={en:{install:'Install DeepRise',ios:'Install on iPhone',how:'Tap Share, then Add to Home Screen',ready:'DeepRise V14.6 is ready to install'},ar:{install:'تثبيت DeepRise',ios:'تثبيت على الآيفون',how:'اضغط مشاركة ثم إضافة إلى الشاشة الرئيسية',ready:'DeepRise V14.6 جاهز للتثبيت'},ru:{install:'Установить DeepRise',ios:'Установить на iPhone',how:'Нажмите Поделиться, затем На экран Домой',ready:'DeepRise V14.6 готов к установке'}};
const t=k=>(copy[L()]||copy.en)[k];let deferred=null;
function brand(){document.title='DeepRise V14.6 PRO';const h=document.querySelector('.brand h1');if(h)h.textContent='⚡ DeepRise V14.6 PRO';const mobileSub=document.querySelector('.dr-mobile-brand small');if(mobileSub)mobileSub.textContent='V14.6 PRO Mobile';const bars=[...document.querySelectorAll('.marketbar span')];const engine=bars.find(x=>/Engine:/i.test(x.textContent||''));if(engine)engine.innerHTML='Engine: <b>V14.6 PRO</b>';const footer=document.querySelector('.footer');if(footer)footer.textContent='DeepRise V14.6 PRO analyses public market data. Signals are probabilistic, not guarantees or financial advice.'}
function languagePerformancePatch(){try{if(typeof languageObserver!=='undefined')languageObserver.disconnect()}catch(e){}let tm=null;const schedule=()=>{clearTimeout(tm);tm=setTimeout(()=>{try{if(typeof applyLanguage==='function')applyLanguage()}catch(e){}},350)};const opt={childList:true,subtree:true};['results','top3','signalResultsPanel'].forEach(id=>{const el=document.getElementById(id);if(el)try{new MutationObserver(schedule).observe(el,opt)}catch(e){}});window.DeepRiseLanguageRefresh=schedule}
if('serviceWorker' in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=stable-v14-6',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{}));
const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
function button(){if(standalone||document.getElementById('deepriseInstall'))return;let b=document.createElement('button');b.id='deepriseInstall';b.textContent='⬇ '+t('install');b.style.cssText='position:fixed;right:14px;bottom:14px;z-index:99998;border:1px solid #35e0a1;background:#071b26;color:#35e0a1;border-radius:14px;padding:12px 16px;font-weight:800;box-shadow:0 10px 30px #0008';b.onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;b.remove();return}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);alert(ios?t('how'):t('ready'))};document.body.appendChild(b)}
function nextCandleLayer(){if(document.getElementById('dr-next-candle-loader'))return;let s=document.createElement('script');s.id='dr-next-candle-loader';s.src='./deeprise-next-candle-v145.js?v=1450';s.defer=true;document.body.appendChild(s)}
function forecastSafetyLayer(){if(document.getElementById('dr-forecast-safety-loader'))return;let s=document.createElement('script');s.id='dr-forecast-safety-loader';s.src='./deeprise-forecast-safety-v145.js?v=1450';s.defer=true;document.body.appendChild(s)}
function uiLayer(){if(document.getElementById('dr-ui-v146-loader'))return;let s=document.createElement('script');s.id='dr-ui-v146-loader';s.src='./deeprise-ui-v146.js?v=1460';s.defer=true;document.body.appendChild(s)}
function tradeMonitorLayer(){if(document.getElementById('dr-trade-monitor-loader'))return;let s=document.createElement('script');s.id='dr-trade-monitor-loader';s.src='./deeprise-trade-monitor-v14.js?v=1440';s.defer=true;document.body.appendChild(s)}
addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;button()});addEventListener('load',()=>{brand();languagePerformancePatch();setTimeout(button,1800);setTimeout(nextCandleLayer,100);setTimeout(forecastSafetyLayer,140);setTimeout(uiLayer,180);setTimeout(tradeMonitorLayer,220);setTimeout(brand,1600)});setTimeout(brand,250);setTimeout(languagePerformancePatch,320);setTimeout(nextCandleLayer,700);setTimeout(forecastSafetyLayer,760);setTimeout(uiLayer,820);setTimeout(tradeMonitorLayer,880);setTimeout(brand,1800);
})();